spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false

barbershop:
  swagger:
    enabled: true
    title: Gentlemens Quarters API
    description: Api for barbershop daily scheduling and website functions
    version: @project.version@
    termsOfServiceUrl: tos
    license: Apache 2.0
    licenseUrl: https://www.apache.org/licenses/LICENSE-2.0
  email:
    address: test@google.com
    host: smtp.gmail.com
    port: 587
    username: test
    password: test
    debug: true