h2:
  tcp:
    enabled: true
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
  main:
    allow-bean-definition-overriding: true

barbershop:
  swagger:
    enabled: true
    title: Gentlemens Quarters API
    description: Api for barbershop daily scheduling and website functions
    version: @project.version@
    termsOfServiceUrl: tos
    license: Apache 2.0
    licenseUrl: https://www.apache.org/licenses/LICENSE-2.0
  email:
    address: gentlemens.quarters.tech@gmail.com
    name: Gentlemen's Quarters
    host: smtp.gmail.com
    port: 587
    username: gentlemens.quarters.tech
    password: ENC(Z+o2GsXBXYfrMScMGoUpM0H7JSaMM30injtpC9pkpXo=)
    debug: true
  registration:
    url: http://localhost:4200/registrationConfirm/

jasypt:
  encryptor:
    bean: encryptorBean
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
