SELECT * FROM ADMIN;
SELECT * FROM APPOINTMENT;
SELECT * FROM AUTH_IDENTIFIER;
SELECT * FROM CUSTOMER;
SELECT * FROM EMPLOYEE;
SELECT * FROM USERS;
SELECT * FROM VERIFICATION_TOKEN;
SELECT * FROM ACCOUNT_DELETION;